#!/bin/bash
if [[ -z "$(poetry env list)" ]]; then
    poetry install --with dev
fi

set -x
poetry run black --check .
poetry run isort --check .
poetry run flake8 .
poetry run mypy
poetry run pytest
